import sys
import unittest
import time
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import HTMLTestRunner
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.common.exceptions import NoSuchElementException
from datetime import datetime
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By

class mate1Profile(unittest.TestCase):
    # Default browser is Firefox
    browser = "firefox"

    def setUp(self):
    	seleniumPath = "C:/Python27/Scripts/selenium_webdrivers"
        if self.browser == "chrome":
            self.driver = webdriver.Chrome(seleniumPath + "/chrome/chromedriver.exe")
            self.driver.implicitly_wait(20) #seconds
            self.driver.maximize_window()
        elif self.browser == "firefox":
            self.driver = webdriver.Firefox()
            self.driver.implicitly_wait(20) #seconds
            self.driver.maximize_window()
        elif self.browser == "edge":
            self.driver = webdriver.Edge(seleniumPath + "/edge/MicrosoftWebDriver.exe")
            self.driver.implicitly_wait(20) #seconds
            self.driver.maximize_window()
    
    def test_valid_login(self):
        driver = self.driver
        try:
            # Login with a valid email & password
            # qatestmate1inc@gmail.com
            # t3ster!@
            driver.get("http://www.mate1.com/")
            self.assertIn("Best Online Dating Site - Free Local Personals & Local Singles | Mate1", driver.title)
            membersArea = driver.find_element_by_xpath("//*[@id='signup']/ul/li[7]/div[2]/a")
            membersArea.click()
            self.driver.switch_to_frame(driver.find_element_by_xpath("//iframe[contains(@src,'http://www.mate1.com/ajax/login?iframe')]"))
            email = driver.find_element_by_xpath("//*[@id='email']")
            email.send_keys("qatestmate1inc@gmail.com")
            password = driver.find_element_by_xpath("//*[@id='password']")
            password.send_keys("t3ster!@")
            loginBtn = driver.find_element_by_xpath("//*[@id='member_login']/div[5]/input")
            loginBtn.click()
            time.sleep(30)
            if (self.driver.title == "Mate1.com - Find someone today"):
                print "Login succesful"
            else:
                print "Login failed or landing page has a different title"
        except NoSuchElementException as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-nosuchelement-%s.png' % now)
            raise e
        except AssertionError as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-assertionerror-%s.png' % now)
            raise e        

    def test_edit_profile_basic_info(self):
        self.test_valid_login()
        driver = self.driver
        try:
            # Navigate to 'Edit my profile' page
            myProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/a")
            myProfile.click()
            editProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/ul/li[2]/a")
            editProfile.click()
            # Validate if it's the correct user profile ('qatestmate1inc')
            self.assertIn('qatestmate1inc', driver.find_element_by_xpath("//*[@id='centerColumn']/div/h1").text)
            # Interact with all basic information fields and enter new data
            title = driver.find_element_by_xpath("//*[@id='title']")
            title.clear()
            title.send_keys("Tester")
            lookingFor = Select(driver.find_element_by_xpath("//*[@id='profileLooking_gender']"))
            lookingFor.select_by_visible_text("Man")
            minAge = Select(driver.find_element_by_xpath("//*[@id='profileLooking_minAge']"))
            minAge.select_by_visible_text("25")
            maxAge = Select(driver.find_element_by_xpath("//*[@id='profileLooking_maxAge']"))
            maxAge.select_by_visible_text("45")
            birthMonth = Select(driver.find_element_by_xpath("//*[@id='month']"))
            birthMonth.select_by_visible_text("October")
            birthDay = Select(driver.find_element_by_xpath("//*[@id='daysOfMonth']"))
            birthDay.select_by_visible_text("20")
            birthYear = Select(driver.find_element_by_xpath("//*[@id='year']"))
            birthYear.select_by_visible_text("1970")
            country = Select(driver.find_element_by_xpath("//*[@id='country']"))
            country.select_by_visible_text("United States")
            postalCode = driver.find_element_by_xpath("//*[@id='input_postalCode']")
            postalCode.clear()
            postalCode.send_keys("10002")
            ethnicity = Select(driver.find_element_by_xpath("//*[@id='ethnicity']"))
            ethnicity.select_by_visible_text("Mixed Race")
            height = Select(driver.find_element_by_xpath("//*[@id='height']"))
            height.select_by_visible_text("6ft. 0in.")
            bodyType = Select(driver.find_element_by_xpath("//*[@id='bodyType']"))
            bodyType.select_by_visible_text("Athletic")
            hairColor = Select(driver.find_element_by_xpath("//*[@id='hairColor']"))
            hairColor.select_by_visible_text("Dark Brown")
            eyeColor = Select(driver.find_element_by_xpath("//*[@id='eyeColor']"))
            eyeColor.select_by_visible_text("Green")
            relationship = Select(driver.find_element_by_xpath("//*[@id='relationship']"))
            relationship.select_by_visible_text("Single")
            children = Select(driver.find_element_by_xpath("//*[@id='children']"))
            children.select_by_visible_text("Grown up")
            wantChildren = Select(driver.find_element_by_xpath("//*[@id='wantChildren']"))
            wantChildren.select_by_visible_text("Undecided")
            religion = Select(driver.find_element_by_xpath("//*[@id='religion']"))
            religion.select_by_visible_text("Catholic")
            study = Select(driver.find_element_by_xpath("//*[@id='educationField']"))
            study.select_by_visible_text("Computer Science")
            occupation = Select(driver.find_element_by_xpath("//*[@id='occupation']"))
            occupation.select_by_visible_text("Computer Engineer")
            education = Select(driver.find_element_by_xpath("//*[@id='education']"))
            education.select_by_visible_text("PhD")
            income = Select(driver.find_element_by_xpath("//*[@id='income']"))
            income.select_by_visible_text("$50,000-$100,000")
            smoking = Select(driver.find_element_by_xpath("//*[@id='smoking']"))
            smoking.select_by_visible_text("Occasionally")
            drinking = Select(driver.find_element_by_xpath("//*[@id='alcohol']"))
            drinking.select_by_visible_text("Often")
            # Submit the new basic information
            saveBtn = driver.find_element_by_xpath("//*[@id='submit_basic_information']")
            saveBtn.click()
            time.sleep(20)
            # Validate if the new data added was saved and shows up on the 'View Profile' page
            self.assertIn('Section updated', driver.find_element_by_xpath("//*[@id='basicInfoUpdated']/ul/li").text)
            self.assertIn('Tester', driver.find_element_by_xpath("//*[@id='basic_information']/div[2]/div[1]").text)
            self.assertIn('Man, 45 years old', driver.find_element_by_xpath("//*[@id='basic_information']/div[2]/div[2]").text)
            self.assertIn('New York, New York', driver.find_element_by_xpath("//*[@id='basic_information']/div[2]/div[3]").text)
            self.assertIn('Mixed Race', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[2]").text)
            self.assertIn('6ft. 0in.', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[4]").text)
            self.assertIn('Athletic', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[6]").text)
            self.assertIn('Dark Brown', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[8]").text)
            self.assertIn('Green', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[10]").text)
            self.assertIn('Single', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[12]").text)
            self.assertIn('Grown up', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[14]").text)
            self.assertIn('Undecided', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[16]").text)
            self.assertIn('Catholic', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[18]").text)
            self.assertIn('Computer Science', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[20]").text)
            self.assertIn('Libra', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[22]").text)
            self.assertIn('Computer Engineer', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[24]").text)
            self.assertIn('PhD', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[26]").text)
            self.assertIn('$50,000-$100,000', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[28]").text)
            self.assertIn('Occasionally', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[30]").text)
            self.assertIn('Often', driver.find_element_by_xpath("//*[@id='basic_information']/ul/li[32]").text)
        except NoSuchElementException as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-nosuchelement-%s.png' % now)
            raise e
        except AssertionError as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-assertionerror-%s.png' % now)
            raise e
    
    def test_edit_profile_text_fields_sanitization(self):
        self.test_valid_login()
        driver = self.driver
        try:
            # Navigate to 'Edit my profile' page
            myProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/a")
            myProfile.click()
            editProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/ul/li[2]/a")
            editProfile.click()
            # Validate if it's the correct user profile ('qatestmate1inc')
            self.assertIn('qatestmate1inc', driver.find_element_by_xpath("//*[@id='centerColumn']/div/h1").text)
            # Input illegal strings in 'About Myself' and 'What I'm Looking For' fields
            aboutMySelf = driver.find_element_by_xpath("//*[@id='aboutMyself']")
            aboutMySelf.clear()
            aboutMySelf.send_keys("www.google.com test@testing.com")
            lookingFor = driver.find_element_by_xpath("//*[@id='lookingFor']")
            lookingFor.clear()
            lookingFor.send_keys("www.google.com test@testing.com")
            # Submit all data
            submitAll = driver.find_element_by_xpath("//*[@id='saveAllContainer']/div[2]/div/center/a")
            submitAll.click()
            time.sleep(20)
            self.assertIn('Section updated', driver.find_element_by_xpath("//*[@id='aboutMyselfUpdated']/ul/li").text)
            self.assertIn('Section updated', driver.find_element_by_xpath("//*[@id='lookingForUpdated']/ul/li").text)
            # Navigate to 'View my profile' page
            myProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/a")
            myProfile.click()
            viewProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/ul/li[1]/a")
            viewProfile.click()
            time.sleep(20)
            # Validate if the illegal strings were stripped from 'About Myself' and 'What I'm Looking For' fields
            self.assertIn('google', driver.find_element_by_xpath("//*[@id='about_myself']/p").text)
            self.assertIn('google', driver.find_element_by_xpath("//*[@id='who_im_looking_for']/p").text)  
        except NoSuchElementException as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-nosuchelement-%s.png' % now)
            raise e
        except AssertionError as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-assertionerror-%s.png' % now)
            raise e

    def test_edit_profile_other_fields(self):
        self.test_valid_login()
        driver = self.driver
        try:
            # Navigate to 'Edit my profile' page
            myProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/a")
            myProfile.click()
            editProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/ul/li[2]/a")
            editProfile.click()
            # Validate if it's the correct user profile ('qatestmate1inc')
            self.assertIn('qatestmate1inc', driver.find_element_by_xpath("//*[@id='centerColumn']/div/h1").text)
            # Insert new data in 'Lifestyle and Interests'
            vegetarian = driver.find_element_by_xpath("//*[@id='diet_3']")
            vegetarian.click()
            balanced = driver.find_element_by_xpath("//*[@id='diet_8']")       
            balanced.click()
            sweets = driver.find_element_by_xpath("//*[@id='diet_6']")       
            sweets.click()
            travelFun = Select(driver.find_element_by_xpath("//*[@id='travelFun']"))
            travelFun.select_by_visible_text("Often")
            travelWork = Select(driver.find_element_by_xpath("//*[@id='travelWork']"))
            travelWork.select_by_visible_text("Often")
            senseHumor = Select(driver.find_element_by_xpath("//*[@id='senseHumor']"))
            senseHumor.select_by_visible_text("Witty")
            workHabits = Select(driver.find_element_by_xpath("//*[@id='workHabits']"))
            workHabits.select_by_visible_text("Flexible hours")
            physicalFitness = Select(driver.find_element_by_xpath("//*[@id='physicalFitness']"))
            physicalFitness.select_by_visible_text("Moderate exercise")
            political = Select(driver.find_element_by_xpath("//*[@id='political']"))
            political.select_by_visible_text("Liberal")
            # Insert new data in 'Favorite Things'
            airline = driver.find_element_by_xpath("//*[@id='profileLikes.airline']")
            airline.clear()
            airline.send_keys("Air Canada")
            artist = driver.find_element_by_xpath("//*[@id='profileLikes.artist']")
            artist.clear()
            artist.send_keys("U2")
            candy = driver.find_element_by_xpath("//*[@id='profileLikes.candy']")
            candy.clear()
            candy.send_keys("Snickers")
            comedian = driver.find_element_by_xpath("//*[@id='profileLikes.comedian']")
            comedian.clear()
            comedian.send_keys("Chris Rock")
            gadget = driver.find_element_by_xpath("//*[@id='profileLikes.gadget']")
            gadget.clear()
            gadget.send_keys("Smartwatch")
            holiday = driver.find_element_by_xpath("//*[@id='profileLikes.holiday']")
            holiday.clear()
            holiday.send_keys("Mexico")
            hangouts = driver.find_element_by_xpath("//*[@id='profileLikes.hangOut']")
            hangouts.clear()
            hangouts.send_keys("McKibbins")
            placeToLive = driver.find_element_by_xpath("//*[@id='profileLikes.placeToLive']")
            placeToLive.clear()
            placeToLive.send_keys("Home")
            software = driver.find_element_by_xpath("//*[@id='profileLikes.software']")
            software.clear()
            software.send_keys("Mate1")
            turnons = driver.find_element_by_xpath("//*[@id='profileLikes.turnOns']")
            turnons.clear()
            turnons.send_keys("Smart people")
            celebrity = driver.find_element_by_xpath("//*[@id='profileLikes.actor']")
            celebrity.clear()
            celebrity.send_keys("Brad Pitt")
            beverage = driver.find_element_by_xpath("//*[@id='profileLikes.beverage']")
            beverage.clear()
            beverage.send_keys("Wine")
            car = driver.find_element_by_xpath("//*[@id='profileLikes.car']")
            car.clear()
            car.send_keys("Tesla")
            movie = driver.find_element_by_xpath("//*[@id='profileLikes.films']")
            movie.clear()
            movie.send_keys("The Curious Case of Benjamin Button")
            game = driver.find_element_by_xpath("//*[@id='profileLikes.game']")
            game.clear()
            game.send_keys("Starcraft")
            hotel = driver.find_element_by_xpath("//*[@id='profileLikes.hotelMotel']")
            hotel.clear()
            hotel.send_keys("Marriott")
            magazine = driver.find_element_by_xpath("//*[@id='profileLikes.magazine']")
            magazine.clear()
            magazine.send_keys("Men's Health")
            politicalFigure = driver.find_element_by_xpath("//*[@id='profileLikes.political']")
            politicalFigure.clear()
            politicalFigure.send_keys("Justin Trudeau")
            sports = driver.find_element_by_xpath("//*[@id='profileLikes.sports']")
            sports.clear()
            sports.send_keys("Barcelona")
            tvshow = driver.find_element_by_xpath("//*[@id='profileLikes.tvShow']")
            tvshow.clear()
            tvshow.send_keys("Game of Thrones")
            animal = driver.find_element_by_xpath("//*[@id='profileLikes.animal']")
            animal.clear()
            animal.send_keys("Dog")
            books = driver.find_element_by_xpath("//*[@id='profileLikes.books']")
            books.clear()
            books.send_keys("Shogun")
            city = driver.find_element_by_xpath("//*[@id='profileLikes.city']")
            city.clear()
            city.send_keys("Boston")
            flower = driver.find_element_by_xpath("//*[@id='profileLikes.flowers']")
            flower.clear()
            flower.send_keys("Roses")
            hero = driver.find_element_by_xpath("//*[@id='profileLikes.hero']")
            hero.clear()
            hero.send_keys("Superman")
            indulgence = driver.find_element_by_xpath("//*[@id='profileLikes.indulgence']")
            indulgence.clear()
            indulgence.send_keys("Cakes")
            music = driver.find_element_by_xpath("//*[@id='profileLikes.music']")
            music.clear()
            music.send_keys("Rock")
            radio = driver.find_element_by_xpath("//*[@id='profileLikes.radio']")
            radio.clear()
            radio.send_keys("Top 40")
            stores = driver.find_element_by_xpath("//*[@id='profileLikes.store']")
            stores.clear()
            stores.send_keys("Hudson Bay")
            virtue = driver.find_element_by_xpath("//*[@id='profileLikes.virtue']")
            virtue.clear()
            virtue.send_keys("Honor")
            appliance = driver.find_element_by_xpath("//*[@id='profileLikes.appliance']")
            appliance.clear()
            appliance.send_keys("Microwave")
            brands = driver.find_element_by_xpath("//*[@id='profileLikes.brands']")
            brands.clear()
            brands.send_keys("Jordan")
            clothing = driver.find_element_by_xpath("//*[@id='profileLikes.clothing']")
            clothing.clear()
            clothing.send_keys("Lewis")
            food = driver.find_element_by_xpath("//*[@id='profileLikes.food']")
            food.clear()
            food.send_keys("Italian")
            hobby = driver.find_element_by_xpath("//*[@id='profileLikes.hobby']")
            hobby.clear()
            hobby.send_keys("Travelling")
            leisure = driver.find_element_by_xpath("//*[@id='profileLikes.leisure']")
            leisure.clear()
            leisure.send_keys("Reading")
            pets = driver.find_element_by_xpath("//*[@id='profileLikes.pets']")
            pets.clear()
            pets.send_keys("Dog")
            season = driver.find_element_by_xpath("//*[@id='profileLikes.season']")
            season.clear()
            season.send_keys("Fall")
            travel = driver.find_element_by_xpath("//*[@id='profileLikes.travel']")
            travel.clear()
            travel.send_keys("Cuba")
            website = driver.find_element_by_xpath("//*[@id='profileLikes.website']")
            website.clear()
            website.send_keys("Google")
            # Insert new data in 'Least Favorite Things'
            dislikeActivity = driver.find_element_by_xpath("//*[@id='profileDislikes.activities']")
            dislikeActivity.clear()
            dislikeActivity.send_keys("Doing nothing")
            dislikeFashion = driver.find_element_by_xpath("//*[@id='profileDislikes.fashion']")
            dislikeFashion.clear()
            dislikeFashion.send_keys("Yoga pants")
            dislikeMusic = driver.find_element_by_xpath("//*[@id='profileDislikes.music']")
            dislikeMusic.clear()
            dislikeMusic.send_keys("Folk")
            dislikeHabits = driver.find_element_by_xpath("//*[@id='profileDislikes.badHabits']")
            dislikeHabits.clear()
            dislikeHabits.send_keys("Lying")
            fears = driver.find_element_by_xpath("//*[@id='profileDislikes.fears']")
            fears.clear()
            fears.send_keys("Fear of heights")
            peeves = driver.find_element_by_xpath("//*[@id='profileDislikes.peeves']")
            peeves.clear()
            peeves.send_keys("Shouting")
            dislikeFood = driver.find_element_by_xpath("//*[@id='profileDislikes.food']")
            dislikeFood.clear()
            dislikeFood.send_keys("Macaroni")
            worstJob = driver.find_element_by_xpath("//*[@id='profileDislikes.job']")
            worstJob.clear()
            worstJob.send_keys("No job at all")
            turnoffs = driver.find_element_by_xpath("//*[@id='profileDislikes.turnOffs']")
            turnoffs.clear()
            turnoffs.send_keys("Loud people")
            evilDoers = driver.find_element_by_xpath("//*[@id='profileDislikes.evilDoers']")
            evilDoers.clear()
            evilDoers.send_keys("Lord Voldemort")
            angry = driver.find_element_by_xpath("//*[@id='profileDislikes.makeAngry']")
            angry.clear()
            angry.send_keys("Liers")
            vices = driver.find_element_by_xpath("//*[@id='profileDislikes.vices']")
            vices.clear()
            vices.send_keys("Heavy smokers")
            # Submit all data
            submitAll = driver.find_element_by_xpath("//*[@id='saveAllContainer']/div[2]/div/center/a")
            submitAll.click()
            time.sleep(20)
            self.assertIn('Section updated', driver.find_element_by_xpath("//*[@id='lifestyleUpdated']/ul/li").text)
            self.assertIn('Section updated', driver.find_element_by_xpath("//*[@id='favoriteThingsUpdated']/ul/li").text)
            self.assertIn('Section updated', driver.find_element_by_xpath("//*[@id='leastFavoriteThingsUpdated']/ul/li").text)
            # Navigate to 'View my profile' page
            myProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/a")
            myProfile.click()
            viewProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/ul/li[1]/a")
            viewProfile.click()
            time.sleep(20)
            # Validate if the new data added in 'Lifestyle and Interests' section shows up on the 'View Profile' page
            self.assertIn('Love sweets, Vegetarian, Balanced', driver.find_element_by_xpath("//*[@id='lifestyle_interests']/ul[1]/li[1]").text)
            self.assertIn('Flexible hours', driver.find_element_by_xpath("//*[@id='lifestyle_interests']/ul[1]/li[2]").text)
            self.assertIn('Moderate exercise', driver.find_element_by_xpath("//*[@id='lifestyle_interests']/ul[1]/li[3]").text)
            self.assertIn('Liberal', driver.find_element_by_xpath("//*[@id='lifestyle_interests']/ul[1]/li[4]").text)
            self.assertIn('Often', driver.find_element_by_xpath("//*[@id='lifestyle_interests']/ul[2]/li[1]").text)
            self.assertIn('Often', driver.find_element_by_xpath("//*[@id='lifestyle_interests']/ul[2]/li[2]").text)
            self.assertIn('Witty', driver.find_element_by_xpath("//*[@id='lifestyle_interests']/ul[2]/li[3]").text)
            # Validate if the new data added in 'Favorite Things' section shows up on the 'View Profile' page
            self.assertIn('Air Canada', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[1]").text)
            self.assertIn('Dog', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[2]").text)
            self.assertIn('U2', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[3]").text)
            self.assertIn('Shogun', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[4]").text)
            self.assertIn('Snickers', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[5]").text)
            self.assertIn('Boston', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[6]").text)
            self.assertIn('Chris Rock', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[7]").text)
            self.assertIn('Roses', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[8]").text)
            self.assertIn('Smartwatch', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[9]").text)
            self.assertIn('Superman', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[10]").text)
            self.assertIn('Mexico', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[11]").text)
            self.assertIn('Cakes', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[12]").text)
            self.assertIn('McKibbins', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[13]").text)
            self.assertIn('Rock', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[14]").text)
            self.assertIn('Home', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[15]").text)
            self.assertIn('Top 40', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[16]").text)
            self.assertIn('Mate1', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[17]").text)
            self.assertIn('Hudson Bay', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[18]").text)
            self.assertIn('Smart people', driver.find_element_by_xpath(".//*[@id='favorite_things']/ul[1]/li[19]").text)
            self.assertIn('Honor', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[1]/li[20]").text)
            self.assertIn('Brad Pitt', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[1]").text)
            self.assertIn('Microwave', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[2]").text)
            self.assertIn('Wine', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[3]").text)
            self.assertIn('Jordan', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[4]").text)
            self.assertIn('Tesla', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[5]").text)
            self.assertIn('Lewis', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[6]").text)
            self.assertIn('The Curious Case of Benjamin Button', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[7]").text)
            self.assertIn('Italian', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[8]").text)
            self.assertIn('Starcraft', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[9]").text)
            self.assertIn('Travelling', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[10]").text)
            self.assertIn('Marriott', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[11]").text)
            self.assertIn('Reading', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[12]").text)
            self.assertIn('Men\'s Health', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[13]").text)
            self.assertIn('Dog', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[14]").text)
            self.assertIn('Justin Trudeau', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[15]").text)
            self.assertIn('Fall', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[16]").text)
            self.assertIn('Barcelona', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[17]").text)
            self.assertIn('Cuba', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[18]").text)
            self.assertIn('Game of Thrones', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[19]").text)
            self.assertIn('Google', driver.find_element_by_xpath("//*[@id='favorite_things']/ul[2]/li[20]").text)
            # Validate if the new data added in 'Least Favorite Things' section shows up on the 'View Profile' page
            self.assertIn('Doing nothing', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[1]/li[1]").text)
            self.assertIn('Macaroni', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[1]/li[2]").text)
            self.assertIn('Yoga pants', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[1]/li[3]").text)
            self.assertIn('No job at all', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[1]/li[4]").text)
            self.assertIn('Folk', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[1]/li[5]").text)
            self.assertIn('Loud people', driver.find_element_by_xpath(".//*[@id='least_favorite_things']/ul[1]/li[6]").text)
            self.assertIn('Lying', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[2]/li[1]").text)
            self.assertIn('Lord Voldemort', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[2]/li[2]").text)
            self.assertIn('Fear of heights', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[2]/li[3]").text)
            self.assertIn('Liers', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[2]/li[4]").text)
            self.assertIn('Shouting', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[2]/li[5]").text)
            self.assertIn('Heavy smokers', driver.find_element_by_xpath("//*[@id='least_favorite_things']/ul[2]/li[6]").text)
        except NoSuchElementException as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-nosuchelement-%s.png' % now)
            raise e
        except AssertionError as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-assertionerror-%s.png' % now)
            raise e

    def test_reset_testing_account(self):
        self.test_valid_login()
        driver = self.driver
        try:
            # Navigate to 'Edit my profile' page
            myProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/a")
            myProfile.click()
            editProfile = driver.find_element_by_xpath("//*[@id='profile_dd_li']/ul/li[2]/a")
            editProfile.click()
            # Validate if it's the correct user profile ('qatestmate1inc')
            self.assertIn('qatestmate1inc', driver.find_element_by_xpath("//*[@id='centerColumn']/div/h1").text)
            # Reset 'Basic information' sheet to default values
            title = driver.find_element_by_xpath("//*[@id='title']")
            title.clear()
            title.send_keys("Wild & crazy software tester")
            lookingFor = Select(driver.find_element_by_xpath("//*[@id='profileLooking_gender']"))
            lookingFor.select_by_visible_text("Woman")
            minAge = Select(driver.find_element_by_xpath("//*[@id='profileLooking_minAge']"))
            minAge.select_by_visible_text("18")
            maxAge = Select(driver.find_element_by_xpath("//*[@id='profileLooking_maxAge']"))
            maxAge.select_by_visible_text("35")
            birthMonth = Select(driver.find_element_by_xpath("//*[@id='month']"))
            birthMonth.select_by_visible_text("January")
            birthDay = Select(driver.find_element_by_xpath("//*[@id='daysOfMonth']"))
            birthDay.select_by_visible_text("1")
            birthYear = Select(driver.find_element_by_xpath("//*[@id='year']"))
            birthYear.select_by_visible_text("1980")
            country = Select(driver.find_element_by_xpath("//*[@id='country']"))
            country.select_by_visible_text("Canada")
            postalCode = driver.find_element_by_xpath("//*[@id='input_postalCode']")
            postalCode.clear()
            postalCode.send_keys("H2W1Y7")
            ethnicity = Select(driver.find_element_by_xpath("//*[@id='ethnicity']"))
            ethnicity.select_by_visible_text("Rather Not Say")
            height = Select(driver.find_element_by_xpath("//*[@id='height']"))
            height.select_by_visible_text("5ft. 6in.")
            bodyType = Select(driver.find_element_by_xpath("//*[@id='bodyType']"))
            bodyType.select_by_visible_text("Rather Not Say")
            hairColor = Select(driver.find_element_by_xpath("//*[@id='hairColor']"))
            hairColor.select_by_visible_text("Rather Not Say")
            eyeColor = Select(driver.find_element_by_xpath("//*[@id='eyeColor']"))
            eyeColor.select_by_visible_text("Rather Not Say")
            relationship = Select(driver.find_element_by_xpath("//*[@id='relationship']"))
            relationship.select_by_visible_text("Rather Not Say")
            children = Select(driver.find_element_by_xpath("//*[@id='children']"))
            children.select_by_visible_text("Rather Not Say")
            wantChildren = Select(driver.find_element_by_xpath("//*[@id='wantChildren']"))
            wantChildren.select_by_visible_text("Rather Not Say")
            religion = Select(driver.find_element_by_xpath("//*[@id='religion']"))
            religion.select_by_visible_text("Rather Not Say")
            study = Select(driver.find_element_by_xpath("//*[@id='educationField']"))
            study.select_by_visible_text("Rather Not Say")
            occupation = Select(driver.find_element_by_xpath("//*[@id='occupation']"))
            occupation.select_by_visible_text("Rather Not Say")
            education = Select(driver.find_element_by_xpath("//*[@id='education']"))
            education.select_by_visible_text("Rather Not Say")
            income = Select(driver.find_element_by_xpath("//*[@id='income']"))
            income.select_by_visible_text("Rather Not Say")
            smoking = Select(driver.find_element_by_xpath("//*[@id='smoking']"))
            smoking.select_by_visible_text("Rather Not Say")
            drinking = Select(driver.find_element_by_xpath("//*[@id='alcohol']"))
            drinking.select_by_visible_text("Rather Not Say")
            # Reset 'About Myself' & 'What I'm looking for' fields
            aboutMySelf = driver.find_element_by_xpath("//*[@id='aboutMyself']")
            aboutMySelf.clear()
            lookingFor = driver.find_element_by_xpath("//*[@id='lookingFor']")
            lookingFor.clear()
            # Reset 'Lifestyle and Interests' section
            vegetarian = driver.find_element_by_xpath("//*[@id='diet_3']")
            vegetarian.click()
            balanced = driver.find_element_by_xpath("//*[@id='diet_8']")       
            balanced.click()
            sweets = driver.find_element_by_xpath("//*[@id='diet_6']")       
            sweets.click()
            travelFun = Select(driver.find_element_by_xpath("//*[@id='travelFun']"))
            travelFun.select_by_visible_text("Rather Not Say")
            travelWork = Select(driver.find_element_by_xpath("//*[@id='travelWork']"))
            travelWork.select_by_visible_text("Rather Not Say")
            senseHumor = Select(driver.find_element_by_xpath("//*[@id='senseHumor']"))
            senseHumor.select_by_visible_text("Rather Not Say")
            workHabits = Select(driver.find_element_by_xpath("//*[@id='workHabits']"))
            workHabits.select_by_visible_text("Rather Not Say")
            physicalFitness = Select(driver.find_element_by_xpath("//*[@id='physicalFitness']"))
            physicalFitness.select_by_visible_text("Rather Not Say")
            political = Select(driver.find_element_by_xpath("//*[@id='political']"))
            political.select_by_visible_text("Rather Not Say")
            # Reset 'Favorite Things' section
            airline = driver.find_element_by_xpath("//*[@id='profileLikes.airline']")
            airline.clear()
            artist = driver.find_element_by_xpath("//*[@id='profileLikes.artist']")
            artist.clear()
            candy = driver.find_element_by_xpath("//*[@id='profileLikes.candy']")
            candy.clear()
            comedian = driver.find_element_by_xpath("//*[@id='profileLikes.comedian']")
            comedian.clear()
            gadget = driver.find_element_by_xpath("//*[@id='profileLikes.gadget']")
            gadget.clear()
            holiday = driver.find_element_by_xpath("//*[@id='profileLikes.holiday']")
            holiday.clear()
            hangouts = driver.find_element_by_xpath("//*[@id='profileLikes.hangOut']")
            hangouts.clear()
            placeToLive = driver.find_element_by_xpath("//*[@id='profileLikes.placeToLive']")
            placeToLive.clear()
            software = driver.find_element_by_xpath("//*[@id='profileLikes.software']")
            software.clear()
            turnons = driver.find_element_by_xpath("//*[@id='profileLikes.turnOns']")
            turnons.clear()
            celebrity = driver.find_element_by_xpath("//*[@id='profileLikes.actor']")
            celebrity.clear()
            beverage = driver.find_element_by_xpath("//*[@id='profileLikes.beverage']")
            beverage.clear()
            car = driver.find_element_by_xpath("//*[@id='profileLikes.car']")
            car.clear()
            movie = driver.find_element_by_xpath("//*[@id='profileLikes.films']")
            movie.clear()
            game = driver.find_element_by_xpath("//*[@id='profileLikes.game']")
            game.clear()
            hotel = driver.find_element_by_xpath("//*[@id='profileLikes.hotelMotel']")
            hotel.clear()
            magazine = driver.find_element_by_xpath("//*[@id='profileLikes.magazine']")
            magazine.clear()
            politicalFigure = driver.find_element_by_xpath("//*[@id='profileLikes.political']")
            politicalFigure.clear()
            sports = driver.find_element_by_xpath("//*[@id='profileLikes.sports']")
            sports.clear()
            tvshow = driver.find_element_by_xpath("//*[@id='profileLikes.tvShow']")
            tvshow.clear()
            animal = driver.find_element_by_xpath("//*[@id='profileLikes.animal']")
            animal.clear()
            books = driver.find_element_by_xpath("//*[@id='profileLikes.books']")
            books.clear()
            city = driver.find_element_by_xpath("//*[@id='profileLikes.city']")
            city.clear()
            flower = driver.find_element_by_xpath("//*[@id='profileLikes.flowers']")
            flower.clear()
            hero = driver.find_element_by_xpath("//*[@id='profileLikes.hero']")
            hero.clear()
            indulgence = driver.find_element_by_xpath("//*[@id='profileLikes.indulgence']")
            indulgence.clear()
            music = driver.find_element_by_xpath("//*[@id='profileLikes.music']")
            music.clear()
            radio = driver.find_element_by_xpath("//*[@id='profileLikes.radio']")
            radio.clear()
            stores = driver.find_element_by_xpath("//*[@id='profileLikes.store']")
            stores.clear()
            virtue = driver.find_element_by_xpath("//*[@id='profileLikes.virtue']")
            virtue.clear()
            appliance = driver.find_element_by_xpath("//*[@id='profileLikes.appliance']")
            appliance.clear()
            brands = driver.find_element_by_xpath("//*[@id='profileLikes.brands']")
            brands.clear()
            clothing = driver.find_element_by_xpath("//*[@id='profileLikes.clothing']")
            clothing.clear()
            food = driver.find_element_by_xpath("//*[@id='profileLikes.food']")
            food.clear()
            hobby = driver.find_element_by_xpath("//*[@id='profileLikes.hobby']")
            hobby.clear()
            leisure = driver.find_element_by_xpath("//*[@id='profileLikes.leisure']")
            leisure.clear()
            pets = driver.find_element_by_xpath("//*[@id='profileLikes.pets']")
            pets.clear()
            season = driver.find_element_by_xpath("//*[@id='profileLikes.season']")
            season.clear()
            travel = driver.find_element_by_xpath("//*[@id='profileLikes.travel']")
            travel.clear()
            website = driver.find_element_by_xpath("//*[@id='profileLikes.website']")
            website.clear()
            # Reset 'Least Favorite Things' section
            dislikeActivity = driver.find_element_by_xpath("//*[@id='profileDislikes.activities']")
            dislikeActivity.clear()
            dislikeFashion = driver.find_element_by_xpath("//*[@id='profileDislikes.fashion']")
            dislikeFashion.clear()
            dislikeMusic = driver.find_element_by_xpath("//*[@id='profileDislikes.music']")
            dislikeMusic.clear()
            dislikeHabits = driver.find_element_by_xpath("//*[@id='profileDislikes.badHabits']")
            dislikeHabits.clear()
            fears = driver.find_element_by_xpath("//*[@id='profileDislikes.fears']")
            fears.clear()
            peeves = driver.find_element_by_xpath("//*[@id='profileDislikes.peeves']")
            peeves.clear()
            dislikeFood = driver.find_element_by_xpath("//*[@id='profileDislikes.food']")
            dislikeFood.clear()
            worstJob = driver.find_element_by_xpath("//*[@id='profileDislikes.job']")
            worstJob.clear()
            turnoffs = driver.find_element_by_xpath("//*[@id='profileDislikes.turnOffs']")
            turnoffs.clear()
            evilDoers = driver.find_element_by_xpath("//*[@id='profileDislikes.evilDoers']")
            evilDoers.clear()
            angry = driver.find_element_by_xpath("//*[@id='profileDislikes.makeAngry']")
            angry.clear()
            vices = driver.find_element_by_xpath("//*[@id='profileDislikes.vices']")
            vices.clear()
            # Submit all data
            submitAll = driver.find_element_by_xpath("//*[@id='saveAllContainer']/div[2]/div/center/a")
            submitAll.click()
            time.sleep(20)
        except NoSuchElementException as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-nosuchelement-%s.png' % now)
            raise e
        except AssertionError as e:
            now = datetime.today().strftime('%Y-%m-%d_%H-%M-%S')
            self.driver.save_screenshot('Errors/screenshot-assertionerror-%s.png' % now)
            raise e

    def tearDown(self):
    	self.driver.close()

def suite():
    suite = unittest.TestSuite()
    suite.addTest(mate1Profile('test_valid_login'))
    suite.addTest(mate1Profile('test_edit_profile_basic_info'))
    suite.addTest(mate1Profile('test_edit_profile_text_fields_sanitization'))
    suite.addTest(mate1Profile('test_edit_profile_other_fields'))
    suite.addTest(mate1Profile('test_reset_testing_account'))
    return suite

if __name__ == "__main__":
    if len(sys.argv) > 1:
        mate1Profile.browser = sys.argv.pop()
    if mate1Profile.browser == "chrome":
        fp = file('mate1Profile_CH.html', 'wb')
        runner = HTMLTestRunner.HTMLTestRunner(
            stream=fp,
            title='Mate1 Profile - Automated Tests Report (Chrome)',
            description='Report generated with HTMLTestRunner.'
            )
        runner.run(suite())
    elif mate1Profile.browser == "firefox":
        fp = file('mate1Profile_FF.html', 'wb')
        runner = HTMLTestRunner.HTMLTestRunner(
            stream=fp,
            title='Mate1 Profile - Automated Tests Report (Firefox)',
            description='Report generated with HTMLTestRunner.'
            )
        runner.run(suite())
    elif mate1Profile.browser == "edge":
        fp = file('mate1Profile_Edge.html', 'wb')
        runner = HTMLTestRunner.HTMLTestRunner(
            stream=fp,
            title='Mate1 Profile - Automated Tests Report (Edge)',
            description='Report generated with HTMLTestRunner.'
            )
        runner.run(suite())